# Generated by Django 4.1.5 on 2023-01-26 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task_app', '0008_alter_s_registration_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s_registration',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='s_registration',
            name='n_emi',
            field=models.CharField(blank=True, default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='s_registration',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
